const orderTableData = [
    {
        id: 1,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'AMSVPEM200127',
        purchase_order_date: '2020-12-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: '1',
                amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'Ari',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
        ],
    },
    {
        id: 2,
        customer_name: 'ARYA ENGINEERING',
        segment: 'INDUSTRIAL MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'AE:PR006:2021:003',
        purchase_order_date: '2021-01-08',
        part_details: [
            {
                id: 1,
                pending_part_name: 'BELLOWSEAL GLOBE VALVE50 NB',
                qty: '4',
                amount: 38000,
                delivery_date: '2020-01-08',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI, IN STOCK',
                part_status: 'Dispatch',
                remarks: '08/01/2021 Dispatch',
            },
        ],
    },
    {
        id: 3,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/0801-05/2021',
        purchase_order_date: '2021-01-08',
        part_details: [
            {
                id: 1,
                pending_part_name: 'TF HEATER ACCESSORIES ERECTION',
                qty: '1',
                amount: 245000,
                delivery_date: '2021-02-14',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARYA ENGINEERING',
                part_status: 'Dispatch',
                remarks: '08/03/2021 Dispatch',
            },
            {
                id: 2,
                pending_part_name:
                    'EXPANSION TANK STRUCTURE FABRICATION & ERECTION WITH EXPANSION TANK',
                qty: '1',
                amount: 110000,
                delivery_date: '2021-02-14',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARYA ENGINEERING',
                part_status: 'Dispatch',
                remarks: '08/03/2021 Dispatch',
            },
            {
                id: 3,
                pending_part_name:
                    'FABRICATION & ERECTION TF PIPING WITH SHOE SUPPORT & 2 NOS PUMP ERECTION WITH ITS FRAME ',
                qty: '1',
                amount: 265000,
                delivery_date: '2021-02-14',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARYA ENGINEERING',
                part_status: 'Dispatch',
                remarks: '08/03/2021 Dispatch',
            },
        ],
    },
    {
        id: 4,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/1301-02/2021',
        purchase_order_date: '2021-01-13',
        part_details: [
            {
                id: 1,
                pending_part_name: 'CS,WCB,Flanged,# 150,Gate Valve 200 MM',
                qty: '5',
                amount: 157704,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'CS,WCB,Flanged,#150,Globe Valve 200 MM',
                qty: '4',
                amount: 133194,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'CS,WCB,Flanged #150 Gate Valve 150 MM',
                qty: '8',
                amount: 164052,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'CS,WCB,Flanged #150 Globe Valve 150 MM',
                qty: '1',
                amount: 25389,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'CS,WCB,Flanged,# 150vGate Valve 100 MM',
                qty: '2',
                amount: 28318,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 6,
                pending_part_name: 'CS, WCB, Flanged,# 150 Globe Valve 100 MM',
                qty: '0',
                amount: null,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '',
            },
            {
                id: 7,
                pending_part_name: 'CS,WCB,Flanged,# 150 Non Return Valve 200 MM',
                qty: '3',
                amount: 98138.25,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 8,
                pending_part_name: 'CS,WCB,Flanged,# 150, Y- Strainer 200 MM',
                qty: '3',
                amount: 110250,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 9,
                pending_part_name: 'FCS,# 800, Socket weld, Globe Valve 15 MM',
                qty: '7',
                amount: 11025,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 10,
                pending_part_name: 'FCS,# 800, Socket weld Gate Valve 15 MM',
                qty: '5',
                amount: 7090,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 11,
                pending_part_name: 'Gasket S.W.G. SS304 + GR with CS outer ring 200 MM',
                qty: '30',
                amount: 7756.2,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 12,
                pending_part_name: 'Gasket S.W.G. SS304 + GR with CS outer ring 150 MM',
                qty: '24',
                amount: 4194.3,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 13,
                pending_part_name: 'Gasket S.W.G. SS304 + GR with CS outer ring 100 MM',
                qty: '6',
                amount: 820.26,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 14,
                pending_part_name: 'Flexible type Expansion bellow for TF line 100 MM',
                qty: '2',
                amount: 25389,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 15,
                pending_part_name: 'Flexible type Expansion bellow for TF line 150 MM',
                qty: '2',
                amount: 31248,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
            {
                id: 16,
                pending_part_name: 'Flexible type Expansion bellow for TF line 200 MM',
                qty: '2',
                amount: 48825,
                delivery_date: '2021-01-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '04/02/2021 Dispatch',
            },
        ],
    },
    {
        id: 5,
        customer_name: 'TROIKAA PHARMACEUTICALS LTD',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4700020324',
        purchase_order_date: '2020-12-14',
        part_details: [
            {
                id: 1,
                pending_part_name: 'Spirex Make PRV VALVE',
                qty: '2',
                amount: 69516,
                delivery_date: '2021-01-08',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',
                part_status: 'Dispatch',
                remarks: 'Dispatch',
            },
        ],
    },
    {
        id: 6,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/1901-03/2021',
        purchase_order_date: '2021-01-19',
        part_details: [
            {
                id: 1,
                pending_part_name: '2 WAY CONTROL VALVE,WCB #150, SIZE 200',
                qty: '1',
                amount: 280125,
                delivery_date: '2021-03-29',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'DEMBLA',

                part_status: 'Dispatch',
                remarks: '08/03/2021 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'Size: 5" x 8", CS conc.reducer, size 125 X 200',
                qty: '2',
                amount: 2149.2,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',

                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'Size: 4" x 8", CS conc.reducer, size 100 X 200',
                qty: '2',
                amount: 2374.2,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',

                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'MS Flange class 150 sorf, od thickness 100',
                qty: '2',
                amount: 1330.2,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',
                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'MS Flange class 150 sorf, od thickness 125',
                qty: '2',
                amount: 1454.4,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',

                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 6,
                pending_part_name: 'MS Flange class 150 sorf, od thickness 200',
                qty: '10',
                amount: 14022,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',
                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
            {
                id: 7,
                pending_part_name: 'Seamless Nipple 1/2", Length: 9" each',
                qty: '6',
                amount: 1434,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',
                part_status: '',
                remarks: '',
            },
            {
                id: 8,
                pending_part_name: 'Bends Seamless MS elbow smls sch.40 b/w rate 1/2"',
                qty: '15',
                amount: 391.5,
                delivery_date: '2021-02-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KANTILAL CHIMANLAL',

                part_status: 'Dispatch',
                remarks: '30/01/2021 Dispatch',
            },
        ],
    },
    {
        id: 7,
        customer_name: 'ROLLCE MANUFACTURING PVT LTD',
        segment: 'MACHINERY MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '20-21/021',
        purchase_order_date: '2021-02-04',
        part_details: [
            {
                id: 1,
                pending_part_name: 'VACCUM RELIEF VALVE',
                qty: '1',
                amount: 584000,
                delivery_date: '2021-04-25',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'PARVA SOLUTION',

                part_status: 'Dispatch',
                remarks: 'DONE',
            },
        ],
    },
    {
        id: 8,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/2502-02/2021',
        purchase_order_date: '2021-02-25',
        part_details: [
            {
                id: 1,
                pending_part_name: 'GATE VALVES 25 NB',
                qty: '10',
                amount: 12065,
                delivery_date: '2021-02-28',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '02/03/2021 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'GATE VALVES, FLANGED 25 NB 300#',
                qty: '1',
                amount: 2515,
                delivery_date: '2021-02-28',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '02/03/2021 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'NIPPLE, 25 NB, 150 MM LONG',
                qty: '7',
                amount: 1778,
                delivery_date: '2021-02-28',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '02/03/2021 Dispatch',
            },
        ],
    },
    {
        id: 9,
        customer_name: 'ROLLCE MANUFACTURING PVT LTD',
        segment: 'MACHINERY MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '20-21/025',
        purchase_order_date: '2021-03-02',
        part_details: [
            {
                id: 1,
                pending_part_name: 'IVGK Make -600 PN16 Valve Seat',
                qty: '2',
                amount: 48000,
                delivery_date: '2021-04-14',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'IN STOCK',

                part_status: 'Dispatch',
                remarks: '27/05/2021 Dispatch',
            },
        ],
    },
    {
        id: 10,
        customer_name: 'STIVAPH HEALTHCARE PVT.LTD',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'STIV/U011/21122020',
        purchase_order_date: '2020-10-28',
        part_details: [
            {
                id: 1,
                pending_part_name:
                    'HP & LP Steam, Compressed air, BOP, Bag Filter - supply and labor',
                qty: '1',
                amount: 463000,
                delivery_date: '',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 11,
        customer_name: 'FOREX EQUIPMENT TRADING ',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'FOREX/008/21-22',
        purchase_order_date: '2021-03-06',
        part_details: [
            {
                id: 1,
                pending_part_name:
                    'Steam Piston Valve F/E for Main steam line #150 size 2" Make GM',
                qty: '2',
                amount: 22230,
                delivery_date: '2021-03-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'GM',

                part_status: 'Dispatch',
                remarks: '9/03/21 Dispatch',
            },
        ],
    },
    {
        id: 12,
        customer_name: 'G-ONE AGRO PRODUCTS LTD',
        segment: 'AGRICULTURE',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'PO-01/2020-2021/rev-00',
        purchase_order_date: '2021-03-05',
        part_details: [
            {
                id: 1,
                pending_part_name:
                    'Thermodynamic typs steam trap-TD-42,BSP thread, Part Code :- 680200,  Size 15 NB',
                qty: '3',
                amount: 15000,
                delivery_date: '2021-04-15',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '07/04/2021 Dispatch',
            },
        ],
    },
    {
        id: 13,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/0403-02/2021',
        purchase_order_date: '2021-03-04',
        part_details: [
            {
                id: 1,
                pending_part_name:
                    'Supply & Erection of MS Ducting for ID Fan to wet scrubber to Chimney-560 mm',
                qty: '1',
                amount: 250000,
                delivery_date: '2021-03-10',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: 'Dispatch',
                remarks: '08/03/2021 Closed',
            },
        ],
    },
    {
        id: 14,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/0403-04/2021',
        purchase_order_date: '2021-03-04',
        part_details: [
            {
                id: 1,
                pending_part_name:
                    'Fabrication & ERECTION OF SHED FOR TF HEATER AS WELL AS FUEL STORAGE PROPOSED SIZE OF ROOM AS BELOW ',
                qty: '1',
                amount: 340000,
                delivery_date: '18/03/20221',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'Durga',

                part_status: 'Dispatch',
                remarks: 'work finish at sight on dated 03/05/2021',
            },
        ],
    },
    {
        id: 15,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'AMLVPEM201420',
        purchase_order_date: '2021-03-10',
        part_details: [
            {
                id: 1,
                pending_part_name: 'Steam Trap Size -15MM',
                qty: '2',
                amount: 10609.2,
                delivery_date: '2021-04-15',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'J K TRADING',

                part_status: 'Dispatch',
                remarks: '13/03/2021 Dispatch',
            },
        ],
    },
    {
        id: 16,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'AMSVPEM200177',
        purchase_order_date: '2021-03-22',
        part_details: [
            {
                id: 1,
                pending_part_name: 'Steam Trap Size -15MM',
                qty: '3',
                amount: 15913,
                delivery_date: '2021-04-15',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'SPIREX',

                part_status: 'Dispatch',
                remarks: '06/04/2021 Dispatch',
            },
        ],
    },
    {
        id: 17,
        customer_name: 'TROIKAA PHARMACEUTICALS LTD',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4700022618',
        purchase_order_date: '2021-03-25',
        part_details: [
            {
                id: 1,
                pending_part_name: 'Drain Trap BPC3, Balance Pressure Thermo Static trap',
                qty: '1',
                amount: 18310,
                delivery_date: '2021-04-14',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'SPIREX',

                part_status: 'Dispatch',
                remarks: '15/04/2021 Dispatch',
            },
        ],
    },
    {
        id: 18,
        customer_name: 'SURENDRANAGAR DISTRICT CO-OP MILK PRO.UNI.LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'E410005922',
        purchase_order_date: '2021-04-19',
        part_details: [
            {
                id: 1,
                pending_part_name: 'ELECTRO PNEUMATIC VALVE POSITIONER',
                qty: '2',
                amount: 228660,
                delivery_date: '2021-04-30',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'SPIREX',

                part_status: 'Dispatch',
                remarks: '24/05/2021 Dispatch',
            },
        ],
    },
    {
        id: 19,
        customer_name: 'ASHTAVINAYAKA TECHNOCRAFTED PVT LTD',
        segment: 'MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '177',
        purchase_order_date: '2021-05-08',
        part_details: [
            {
                id: 1,
                pending_part_name: '',
                qty: '5',
                amount: null,
                delivery_date: '',
                engineer_name: '',
                vendor_name: '',

                part_status: {
                    DISPATCH: '',
                },
                remarks: '',
            },
        ],
    },
    {
        id: 20,
        customer_name: 'TROIKAA PHARMACEUTICALS LTD',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4700023417',
        purchase_order_date: '2021-05-06',
        part_details: [
            {
                id: 1,
                pending_part_name: 'INTEGRAL ORIFICE ASSLY',
                qty: '1',
                amount: 76008,
                delivery_date: '2021-05-30',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ELECTRONET',

                part_status: 'DISPATCH',
                remarks: '05/07/2021 DISPATCH',
            },
        ],
    },
    {
        id: 21,
        customer_name: 'TROIKAA PHARMACEUTICALS LTD',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4700023559',
        purchase_order_date: '2021-05-07',
        part_details: [
            {
                id: 1,
                pending_part_name: '',
                qty: '1',
                amount: 44329,
                delivery_date: '2021-05-22',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'VEZA',

                part_status: 'DISPATCH',
                remarks: '22/05/2021 Dispatch',
            },
        ],
    },
    {
        id: 22,
        customer_name: 'ASHTAVINAYAKA TECHNOCRAFTED PVT LTD',
        segment: 'MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '249',
        purchase_order_date: '2021-06-02',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM STRAINER & STEAM TRAP',
                qty: '5',
                amount: 61152,
                delivery_date: '10/6/2021 & 05/06/2021',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'SPIREX',

                part_status: 'DISPATCH',
                remarks: '25/6/2021 DISPATCH',
            },
        ],
    },
    {
        id: 23,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'AMLVPEM21220321',
        purchase_order_date: '2021-06-11',
        part_details: [
            {
                id: 1,
                pending_part_name: 'BOILER FEED WATER VALVE ',
                qty: '2',
                amount: null,
                delivery_date: '2021-06-15',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'J K TRADING',

                part_status: 'DISPATCH',
                remarks: ' ',
            },
        ],
    },
    {
        id: 24,
        customer_name: 'ROLLCE MANUFACTURING PVT LTD',
        segment: 'MACHINERY MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '21',
        purchase_order_date: '2021-02-04',
        part_details: [
            {
                id: 1,
                pending_part_name: 'VALVES',
                qty: '1 LOT',
                amount: 584000,
                delivery_date: '2021-04-25',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'GM,PRIME,GG,DEMBLA,ARI',

                part_status: 'DISPATCH',
                remarks: 'DONE',
            },
        ],
    },
    {
        id: 25,
        customer_name: 'ARVIND ENVISOL LTD',
        segment: 'INFRASTRUCTURE',
        payment_status: 'PENDING',
        purchase_order_no: '4400012769',
        purchase_order_date: '2021-06-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'DESUPERHEATER',
                qty: '1 set',
                amount: 354213,
                delivery_date: '2021-08-02',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'MECASTER',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 26,
        customer_name: 'FOREX EQUIPMENT TRADING',
        segment: '',
        payment_status: ' ',
        purchase_order_no: 'BY MAIL',
        purchase_order_date: '2021-06-19',
        part_details: [
            {
                id: 1,
                pending_part_name: 'PRV  ',
                qty: 1,
                amount: 32000,
                delivery_date: '2021-07-23',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'MECASTER',

                part_status: 'DISPATCH',
                remarks: '21/7/2021 DISPATCH',
            },
        ],
    },
    {
        id: 27,
        customer_name: 'SRUZAM LABS PVT LTD',
        segment: 'PHARMA',
        payment_status: 'PENDING',
        purchase_order_no: '42',
        purchase_order_date: '2021-06-30',
        part_details: [
            {
                id: 1,
                pending_part_name: '',
                qty: '6 SET',
                amount: 500501,
                delivery_date: '2021-07-21',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 28,
        customer_name: 'N K PROTEIN ',
        segment: ' ',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4500259965',
        purchase_order_date: '2021-06-25',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM CONTROL VALVE',
                qty: '1',
                amount: 50151,
                delivery_date: '2021-07-02',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'DEMBLA',

                part_status: 'DISPATCH',
                remarks: '03/08/2021 DISPATCH',
            },
        ],
    },
    {
        id: 29,
        customer_name: 'GOPAL SNACKS PVT LTD',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'GSPL/0307-001-2021',
        purchase_order_date: '2021-07-03',
        part_details: [
            {
                id: 1,
                pending_part_name: 'GLOBE VALVE & CONTROL VALVE',
                qty: '2',
                amount: 94000,
                delivery_date: '2021-08-09',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'WELLCAST , DEMBLA',

                part_status: 'DISPATCH',
                remarks: '01/09/2021 DISPATCH',
            },
        ],
    },
    {
        id: 30,
        customer_name: ' SUVIRA UTILITY SERVICES PVT. LTD.',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'SU/PO/2021011/08/166',
        purchase_order_date: '2021-06-28',
        part_details: [
            {
                id: 1,
                pending_part_name: 'GATE & NRV VALVE',
                qty: '4',
                amount: 200000,
                delivery_date: '2021-08-09',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'L & T',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 31,
        customer_name: 'ARCHEAN CHEMICAL INDUSTRIES PVT LTD',
        segment: 'CHEMICAL INDUSTRY',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '1000011050',
        purchase_order_date: '2021-07-12',
        part_details: [
            {
                id: 1,
                pending_part_name: 'PRESSURE CONTROL VALVE GLOBE TYPE 8"',
                qty: '1',
                amount: 970000,
                delivery_date: '2021-11-12',
                engineer_name: 'DC,DILIP SIR',
                vendor_name: 'ARI',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 32,
        customer_name: 'N K PROTEIN ',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4500261472',
        purchase_order_date: '2021-07-12',
        part_details: [
            {
                id: 1,
                pending_part_name: 'ACTUCATOR VALVE DELVAL ECF-100',
                qty: '2',
                amount: 22500,
                delivery_date: '',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'STOCK IN OUR GODOWN',

                part_status: 'DISPATCH',
                remarks: '03/08/2021 DISPATCH',
            },
        ],
    },
    {
        id: 33,
        customer_name: 'BANAS DAIRY',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'RECEIVED',
        purchase_order_no: 'B410247521',
        purchase_order_date: '2021-07-10',
        part_details: [
            {
                id: 1,
                pending_part_name: 'BALL VALVE',
                qty: '2',
                amount: 27810,
                delivery_date: '2021-07-22',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'WELLCAST',

                part_status: 'DISPATCH',
                remarks: '22/7/2021 DISPATCH',
            },
        ],
    },
    {
        id: 34,
        customer_name: 'BANAS DAIRY',
        segment: 'FOOD & BEVERAGES',
        payment_status: 'PENDING',
        purchase_order_no: 'B410247795',
        purchase_order_date: '2021-07-14',
        part_details: [
            {
                id: 1,
                pending_part_name: 'SEATLESS & GLANDESS PISTON VALVE 80NB',
                qty: '16',
                amount: 173040,
                delivery_date: '2021-08-18',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'JP ENGINEERING',

                part_status: 'DISPATCH',
                remarks: '23/7/2021 DISPATCH',
            },
        ],
    },
    {
        id: 35,
        customer_name: 'NATURE FRESH INDUSTRIES LTD',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'PO-01/2021-2022/REV-00',
        purchase_order_date: '2021-07-15',
        part_details: [
            {
                id: 1,
                pending_part_name: '70 ITEMS',
                qty: '70',
                amount: 277700,
                delivery_date: '6 WEEK',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'WELLCAST,GM,KC,PRIME,SPIRAX',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 36,
        customer_name: 'ZYDUS CADILA',
        segment: 'PHARMA',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '4490126074',
        purchase_order_date: '2021-07-15',
        part_details: [
            {
                id: 1,
                pending_part_name: 'VALVES',
                qty: '38',
                amount: 202079,
                delivery_date: '2021-07-31',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'GM,PRIME,SPIRAX',

                part_status: 'DISPATCH',
                remarks: '29/7/2021 DISPATCH',
            },
        ],
    },
    {
        id: 37,
        customer_name: 'BHARAT BIOTECH ',
        segment: '',
        payment_status: 'RECEIVED',
        purchase_order_no: 'BBIL/BVPN/PUR/109',
        purchase_order_date: '2021-07-17',
        part_details: [
            {
                id: 1,
                pending_part_name: 'SAFETY VALVE',
                qty: '2',
                amount: 53800,
                delivery_date: '2021-07-23',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'KC',

                part_status: 'DISPATCH',
                remarks: '',
            },
        ],
    },
    {
        id: 38,
        customer_name: ' SUVIRA UTILITY SERVICES PVT. LTD.',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'SU/PO/2021011/12/179',
        purchase_order_date: '2021-07-17',
        part_details: [
            {
                id: 1,
                pending_part_name: 'GLOBE VALVE  ',
                qty: '1',
                amount: 125000,
                delivery_date: '2021-08-07',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: '',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 39,
        customer_name: 'i-Kcal Systems Engineering LLP',
        segment: '',
        payment_status: 'RECEIVED',
        purchase_order_no: 'BY MAIL CONFORMATION',
        purchase_order_date: '2021-08-04',
        part_details: [
            {
                id: 1,
                pending_part_name: 'VALVE,GASKET',
                qty: '18',
                amount: 95350,
                delivery_date: '2021-09-01',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'PRIME,JKT,V-TECH',
                EXPENSE: 900,
                part_status: 'DISPATCH',
                remarks: '20/8/2021 DISPATCH',
            },
        ],
    },
    {
        id: 40,
        customer_name: 'DEEPSHIKHA EXIM PVT. LTD.(Amitara)',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'BY MAIL',
        purchase_order_date: '2021-08-14',
        part_details: [
            {
                id: 1,
                pending_part_name: 'FLOW METER,VALVE',
                qty: '3',
                amount: 229228,
                delivery_date: '2021-09-30',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'VNC, DEMBLA',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 41,
        customer_name: 'BIOVET PVT LTD',
        segment: '',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: 'BIOVET/BVPN/PUR/72',
        purchase_order_date: '2021-08-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'PRESURE REDUCING VALVE',
                qty: '1',
                amount: 171000,
                delivery_date: '2021-08-24',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'FLUIDTECH ',

                part_status: 'DISPATCH',
                remarks: '24/8/2021 DISPATCH',
            },
        ],
    },
    {
        id: 42,
        customer_name: 'ROLLCE MANUFACTURING PVT LTD',
        segment: 'MACHINERY MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: ' 21-22/051\n',
        purchase_order_date: '2021-08-24',
        part_details: [
            {
                id: 1,
                pending_part_name: 'LHP MOTOR',
                qty: '4',
                amount: 589444,
                delivery_date: '2021-10-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'LHP MOTOR',

                part_status: '',
                remarks: '',
            },
        ],
    },
    {
        id: 43,
        customer_name: 'ROLLCE MANUFACTURING PVT LTD',
        segment: 'MACHINERY MANUFACTURER',
        payment_status: 'Complete',
        status: 'Dispatched',
        purchase_order_no: '21-22/052',
        purchase_order_date: '2021-08-24',
        part_details: [
            {
                id: 1,
                pending_part_name: 'LHP MOTOR',
                qty: '2',
                amount: 340556,
                delivery_date: '2021-10-19',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'LHP MOTOR',

                part_status: '',
                remarks: '',
            },
        ],
    },
];
export default orderTableData;
