const orderTableData = [
    {
        id: 1,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        purchase_order_no: 'AMSVPEM200127',
        purchase_order_date: '2020-12-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 10,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
        ],
        status: 'Dispatched',
    },
    {
        id: 2,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        purchase_order_no: 'AMSVPEM200127',
        purchase_order_date: '2020-12-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 10,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
        ],
        status: 'Dispatched',
    },
    {
        id: 3,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        purchase_order_no: 'AMSVPEM200127',
        purchase_order_date: '2020-12-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 10,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
        ],
        status: 'Dispatched',
    },
    {
        id: 4,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        purchase_order_no: 'AMSVPEM200127',
        purchase_order_date: '2020-12-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 10,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
        ],
        status: 'Dispatched',
    },
    {
        id: 5,
        customer_name: 'AMANTA HEALTHCARE LIMITED',
        segment: 'PHARMA',
        payment_status: 'Complete',
        purchase_order_no: 'AMSVPEM200127',
        purchase_order_date: '2020-12-21',
        part_details: [
            {
                id: 1,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 10,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 2,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 3,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 4,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
            {
                id: 5,
                pending_part_name: 'STEAM TRAP 1/2"',
                qty: 15,
                total_amount: 10200,
                delivery_date: '2021-01-05',
                engineer_name: 'Dhruval Chotaliya',
                engineer_initials: 'DC',
                vendor_name: 'ARI',
                part_status: 'Dispatch',
                remarks: '23-12-2020 Dispatch',
            },
        ],
        status: 'Dispatched',
    },
];

export default orderTableData;
